name: Github Action Workflow for Terraform CI/CD to AWS Cloud

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  terraform:
    name: 'Deploy'
    runs-on: self-hosted
    environment: production

# This is to make sure no concurrent jobs
    concurrency:
     group: terraform-production
     cancel-in-progress: false

#    defaults: 
 #     run:
  #      working-directory: Terraform

    env:
      AWS_REGION: 'us-east-1'
      TF_VERSION: '1.14.3'

    steps:
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v2

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Format'
      run: terraform fmt

    - name: 'Terraform Validate'
      run: terraform validate

    - name: 'Terraform Plan'
      run: terraform plan -out=tfplan

    - name: 'Terraform Apply'
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve tfplan
